# Generated by Django 5.1.7 on 2025-03-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotterApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_distance_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fuel', 'Fuel Stop'), ('Pickup', 'Pickup'), ('Dropoff', 'Dropoff')], max_length=10)),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('duration_minutes', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='spotterApi.trip')),
            ],
        ),
    ]
