# Generated by Django 5.1.7 on 2025-03-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotterApi', '0002_trip_route_geometry_trip_total_distance_miles_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
